spring:
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        enabled: true
        max-active: 10
        max-idle: 10
        max-wait: 100000
    timeout: 5000
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    port: 465
    username: twq3137@qq.com
    password: znaktxurzyzibebb
    properties:
      mail:
        smtp:
          ssl:
            enable: true


# 日志打印设置
logging:
  pattern:
#    level: "%5p [${spring.zipkin.service.name:${spring.application.name:-}},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}][%X{clientId}:%X{username}:%X{realRemoteAddr}]"
#    file: "%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}} ${LOG_LEVEL_PATTERN:${logging.pattern.level}} [%t] %logger{39}:%L - %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
    console: "${CONSOLE_LOG_PATTERN:%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:${logging.pattern.level}}) %clr([%t]){faint} %clr(%logger{39}){cyan}:%L %clr(-){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}}"
  level:
    root: info

# 文件服务
file:
  # 存储文件的根目录
  rootDirectory: E:/Download/repair
  # python算法结果文件
  resultFileName: result.txt
